#!/usr/bin/env python3
"""
Bundle player data from the Flask app's cache into players.js for the extension.

Run from the best-ball-extension directory:
    python generate_players.py

Or run from anywhere:
    python /path/to/best-ball-extension/generate_players.py
"""
import json
import os
import sys

CACHE_PATH = os.path.join(
    os.path.dirname(__file__),
    '../best-ball-draft/app/data/player_cache.json'
)
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), 'players.js')


def main():
    if not os.path.exists(CACHE_PATH):
        print(f'Error: cache not found at {CACHE_PATH}')
        print('Run the Flask app and call POST /api/players/refresh first.')
        sys.exit(1)

    with open(CACHE_PATH) as f:
        data = json.load(f)

    players = data.get('players', [])
    season  = data.get('season', 'unknown')

    if not players:
        print('Error: cache is empty. Re-fetch player data first.')
        sys.exit(1)

    with open(OUTPUT_PATH, 'w') as f:
        f.write(f'// Auto-generated by generate_players.py — {len(players)} players, season {season}\n')
        f.write('// Re-run generate_players.py after refreshing player data in the Flask app.\n')
        f.write('const PLAYERS = ')
        json.dump(players, f, separators=(',', ':'))
        f.write(';\n')

    print(f'✓ players.js written — {len(players)} players, season {season}')


if __name__ == '__main__':
    main()
